### ISSUE TITLE
Create new account - place the correct logo and rearrange the place of login buttons

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#1]
1. place the correct logo and rearrange the place of login buttons
2. add this in buttom Website Terms of Use | Website Privacy Policy | Policies | Feedback | Request Transcript | FAQ | Contact Us © 2020 Silicon Valley High School, Inc.

url : https://lms.svhs.co/
![image](https://user-images.githubusercontent.com/57624263/140884582-a49c07da-aa23-47dd-9bb0-f53d22ebe13f.png)
![image](https://user-images.githubusercontent.com/57624263/140885884-ccf6b70e-9b1e-416d-bbcd-2f7d87b92c8f.png)

**Comment by ajayacube** [comment]
Login form is replace by button, now design issue has been fixed

**Comment by afshanacube** [comment]
QA partially passed for only 2 point.
![image](https://user-images.githubusercontent.com/57624263/143435930-235b8564-0899-40f8-94d4-fc9899c35027.png)

**Comment by afshanacube** [comment]
QA partially passed for only 2 point.
![image](https://user-images.githubusercontent.com/57624263/143435930-235b8564-0899-40f8-94d4-fc9899c35027.png)

**Comment by afshanacube** [comment]
another ticket is opened for logo issue. #11
