### ISSUE TITLE
Full name of the course are not displaying.

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#10]
course names are not properly displaying. half of the name is not displaying.

url : https://lms.svhs.co/

![image](https://user-images.githubusercontent.com/57624263/143434715-0fcb5d00-bc2c-41f9-8493-edd752f7ab0a.png)

**Comment by ajayacube** [comment]
I have check on all device in mozilla firfox mobile view and its done,looking well,for some course the course name content is high thats why its breaking .

**Comment by ajayacube** [comment]
![image](https://user-images.githubusercontent.com/93391399/145047321-5109aaae-a0e5-4669-afb0-6dd430f9bd16.png)
 Issue resolved

**Comment by afshanacube** [comment]
QA Passed.
![image](https://user-images.githubusercontent.com/57624263/145335543-479d40ea-1032-464a-be26-c2e208526623.png)
