### ISSUE TITLE
Quiz navigation box is not displaying. 

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#17]
Quiz navigation box is not displaying neither in quiz page nor in quiz submitting page.
url : https://lms.svhs.co/mod/quiz/summary.php?attempt=1995500&cmid=29239
![image](https://user-images.githubusercontent.com/57624263/143530046-e067a1fd-7908-4cd3-8b9d-bf9f89994e54.png)

![image](https://user-images.githubusercontent.com/57624263/143529898-0876a846-b55c-4e85-8977-180de366fe84.png)

**Comment by ajayacube** [comment]
This will look for admin view,student cant view the attempt this is not issue.
![image](https://user-images.githubusercontent.com/93391399/144858275-d335db19-9f55-4952-912f-7d7593dec08f.png)

**Comment by afshanacube** [comment]
Well ur not in a correct page. the screenshot u attched is not correct

**Comment by afshanacube** [comment]
![image](https://user-images.githubusercontent.com/57624263/144898886-5d55e999-6dca-475e-abd2-1f41880a80df.png)

**Comment by afshanacube** [comment]
David is ok with not having navigation box in mobile view
