### ISSUE TITLE
home page menu bar is missing

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#2]
After logging, in home page display menu bar like  Dashboard, My Courses, Course Catalog, Request Transcript and Tutoring
url : https://lms.svhs.co/
![image](https://user-images.githubusercontent.com/57624263/140886870-844f3d20-b0c7-4ff7-8abc-92c6f9a3d53e.png)

**Comment by ajayacube** [comment]
Issue resolved
![image](https://user-images.githubusercontent.com/93391399/144594232-ba2d7b30-3cb9-4703-8e65-7e05e37dd8fa.png)

**Comment by afshanacube** [comment]
QA passed
