### ISSUE TITLE
 Videos are displaying only half. Other half is hidden.

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#6]
Videos are displaying only half. Other half is hidden.
![image](https://user-images.githubusercontent.com/57624263/140916098-f9e69ad0-5a77-4bbe-8a84-43d9dfe57a0b.png)

**Comment by ajayacube** [comment]
![image](https://user-images.githubusercontent.com/93391399/144856530-7e6131e5-a96c-4fbc-b73d-5a1b6f036755.png)

Issue is resolve. but we have to set change css in iframe every where video is imbedded

**Comment by afshanacube** [comment]
QA failed.
![image](https://user-images.githubusercontent.com/57624263/144858557-68416363-499c-442c-9244-7c926cb0b8fb.png)

**Comment by afshanacube** [comment]
QA passed
![image](https://user-images.githubusercontent.com/57624263/145334441-b7ae4f0d-6467-429d-ba33-ff666da8ac5c.png)
