### ISSUE TITLE
 Displaying loading problem page when I try to submit the quiz by clicking on finish button

### ISSUE THREAD

**Issue by afshanacube** [afshanacube/SVHS---PO-system#8]
Displaying loading problem page when I try to submit the quiz by clicking on finish button
![image](https://user-images.githubusercontent.com/57624263/140916311-4e234aef-64f3-43cd-ac40-e427748a0a47.png)

after clicking on reload button saying 400 bad request
![image](https://user-images.githubusercontent.com/57624263/140916680-ef9ec83c-954f-4e43-a395-c3fd5689b5f1.png)

**Comment by ajayacube** [comment]
That was internet issue ,i debug and found its working fine

**Comment by afshanacube** [comment]
QA Passed.
![image](https://user-images.githubusercontent.com/57624263/143532142-58f4eeaf-3da9-47c1-b7c0-a1735abe919d.png)
